name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.25'
      - name: Build
        shell: bash
        run: |
          export GOARCH=${{ matrix.arch }}
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            go build -o bin/scrubectl-${{ matrix.os }}-${{ matrix.arch }}.exe
          else
            go build -o bin/scrubectl-${{ matrix.os }}-${{ matrix.arch }}
          fi
      - name: Test
        run: go test ./pkg/...
      - name: Format
        run: go fmt ./... && git diff --exit-code
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scrubectl-${{ matrix.os }}-${{ matrix.arch }}
          path: bin/scrubectl-${{ matrix.os }}-${{ matrix.arch }}